import { requireAdmin } from "@/lib/auth/session";
import { getDatabase } from "@/lib/db";
import { AdminForm, type AdminField } from "@/components/features/admin-form";
import { AdminPagination, parseAdminSearch, type AdminSearch } from "@/components/features/admin-list";
function fields(c?:{name:string;slug:string;description:string|null;image:string|null;isArchived:boolean}):AdminField[]{return [{name:"name",label:"Nom",value:c?.name},{name:"slug",label:"Slug",value:c?.slug},{name:"description",label:"Description",type:"textarea",value:c?.description??"",required:false},{name:"image",label:"Image (URL facultative)",value:c?.image??"",required:false},{name:"isArchived",label:"Archivée — masquée avec ses produits",type:"checkbox",value:c?.isArchived?"on":""}];}
export default async function CategoriesPage({searchParams}:{searchParams:Promise<AdminSearch>}){
 await requireAdmin();const db=getDatabase(),{filters,invalid}=parseAdminSearch(await searchParams),where={name:{contains:filters.q,mode:"insensitive" as const}};
 const count=await db.category.count({where}),pages=Math.max(1,Math.ceil(count/20)),page=Math.min(filters.page,pages);
 const categories=await db.category.findMany({where,orderBy:[{name:"asc"},{id:"asc"}],take:20,skip:(page-1)*20,include:{_count:{select:{products:true}}}});
 return <main id="contenu" tabIndex={-1} className="shop-main"><h1 className="page-title">Catégories</h1>{invalid&&<p role="alert">Filtre invalide.</p>}<form className="admin-filters"><label htmlFor="category-q">Nom</label><input id="category-q" name="q" defaultValue={filters.q} maxLength={120}/><button className="cta">Rechercher</button></form><div className="account-grid">{categories.map(c=><section className="artisan-panel" key={c.id}><h2>{c.name}</h2><p>{c._count.products} produit(s) · {c.isArchived?"Archivée":"Active"}</p><details><summary>Modifier</summary><AdminForm operation="category" id={c.id} fields={fields(c)} label="Enregistrer la catégorie"/></details>{!c._count.products&&<AdminForm operation="category-delete" id={c.id} label="Supprimer cette catégorie vide" confirm/>}</section>)}</div>{!categories.length&&<p>Aucune catégorie.</p>}<AdminPagination page={page} pages={pages} query={filters}/><section className="artisan-panel"><h2>Nouvelle catégorie</h2><AdminForm operation="category" fields={fields()} label="Créer la catégorie"/></section></main>;
}
