import { requireAdmin } from "@/lib/auth/session";
import { getDatabase } from "@/lib/db";
import { AdminForm, type AdminField } from "@/components/features/admin-form";
import { AdminPagination, parseAdminSearch, type AdminSearch } from "@/components/features/admin-list";
function fields(p?:{code:string;type:string;value:number;expiresAt:Date|null;maxUses:number|null;isActive:boolean}):AdminField[]{return [{name:"code",label:"Code",value:p?.code},{name:"type",label:"Type",value:p?.type??"PERCENT",options:[{value:"PERCENT",label:"Pourcentage"},{value:"FIXED",label:"Montant fixe (€)"},{value:"FREE_SHIPPING",label:"Port offert"}]},{name:"value",label:"Valeur : % entier ou euros",value:p?String(p.type==="FIXED"?p.value/100:p.value):"10",help:"Pourcentage 1 à 100 ; montant en euros ; 0 pour le port offert."},{name:"expiresAt",label:"Expiration UTC (facultative)",value:p?.expiresAt?.toISOString()??"",required:false,help:"Format AAAA-MM-JJTHH:mm:ssZ, par exemple 2027-01-31T22:59:59Z. Vide : aucune expiration."},{name:"maxUses",label:"Maximum d’utilisations (facultatif)",value:p?.maxUses===null||p?.maxUses===undefined?"":String(p.maxUses),required:false,help:"Vide : sans limite. Les utilisations consommées sont conservées."},{name:"isActive",label:"Promotion active",type:"checkbox",value:p?.isActive===false?"":"on"}];}
export default async function PromotionsPage({searchParams}:{searchParams:Promise<AdminSearch>}){
 await requireAdmin();const db=getDatabase(),{filters,invalid}=parseAdminSearch(await searchParams),where={code:{contains:filters.q,mode:"insensitive" as const}};
 const count=await db.promoCode.count({where}),pages=Math.max(1,Math.ceil(count/20)),page=Math.min(filters.page,pages);
 const promos=await db.promoCode.findMany({where,orderBy:[{code:"asc"},{id:"asc"}],take:20,skip:(page-1)*20});
 return <main id="contenu" tabIndex={-1} className="shop-main"><h1 className="page-title">Promotions</h1>{invalid&&<p role="alert">Filtre invalide.</p>}<form className="admin-filters"><label htmlFor="promo-q">Code</label><input id="promo-q" name="q" defaultValue={filters.q} maxLength={120}/><button className="cta">Rechercher</button></form><div className="account-grid">{promos.map(p=><section className="artisan-panel" key={p.id}><h2>{p.code}</h2><p>{p.isActive?"Active":"Inactive"} · {p.usedCount} utilisation(s){p.maxUses?` sur ${p.maxUses}`:""}</p><details><summary>Modifier la promotion</summary><AdminForm operation="promo" id={p.id} fields={fields(p)} label="Enregistrer la promotion"/></details></section>)}</div>{!promos.length&&<p>Aucune promotion.</p>}<AdminPagination page={page} pages={pages} query={filters}/><section className="artisan-panel"><h2>Nouvelle promotion</h2><AdminForm operation="promo" fields={fields()} label="Créer la promotion"/></section></main>;
}
