"use client";
import { useActionState, useEffect, useId, useRef, useState } from "react";
import { submitDelivery } from "@/app/(shop)/commande/actions";
import { relayPoints, type CheckoutState } from "@/lib/checkout/validation";
type Address = { id: string; firstName: string; lastName: string; line1: string; line2: string | null; city: string; zip: string; isDefault: boolean };
export function DeliveryForm({ email = "", firstName = "", lastName = "", addresses = [] }: { email?: string; firstName?: string; lastName?: string; addresses?: Address[] }) {
  const [state, action, pending] = useActionState(submitDelivery, { message: "" } as CheckoutState);
  const [addressId, setAddressId] = useState(addresses.find(address => address.isDefault)?.id ?? "");
  const address = addresses.find(address => address.id === addressId);
  const id = useId(), form = useRef<HTMLFormElement>(null);
  useEffect(() => { if (state.errors) form.current?.querySelector<HTMLInputElement>('[aria-invalid="true"]')?.focus(); }, [state]);
  const labels: Record<string, string> = { firstName: "Prénom", lastName: "Nom", line1: "Adresse", line2: "Complément d’adresse (facultatif)", city: "Ville", zip: "Code postal" };
  const autocomplete: Record<string, string> = { firstName: "given-name", lastName: "family-name", line1: "address-line1", line2: "address-line2", city: "address-level2", zip: "postal-code" };
  function field(key: string, label: string, defaults: string, billing = false) {
    const name = billing ? `billing${key.replace(/^./, char => char.toUpperCase())}` : key;
    return <div key={name}><label htmlFor={`${id}-${name}`}>{label}</label><input id={`${id}-${name}`} name={name} defaultValue={state.values?.[name] ?? defaults} autoComplete={`${billing ? "billing" : "shipping"} ${autocomplete[key]}`} required={!billing && key !== "line2"} maxLength={key === "zip" ? 5 : 100} inputMode={key === "zip" ? "numeric" : undefined} aria-invalid={Boolean(state.errors?.[name]?.length)} aria-describedby={state.errors?.[name] ? `${id}-${name}-error` : undefined} />{state.errors?.[name] && <p id={`${id}-${name}-error`} className="field-error">{state.errors[name].join(" ")}</p>}</div>;
  }
  return <form ref={form} action={action} className="auth-form delivery-form" aria-busy={pending}><input type="hidden" name="intent" value="delivery" /><input type="hidden" name="country" value="FR" />{state.message && <p role="alert" className="field-error">{state.message}</p>}
    <div><label htmlFor={`${id}-email`}>Email du récapitulatif</label><input id={`${id}-email`} name="email" type="email" required autoComplete="email" maxLength={254} defaultValue={state.values?.email ?? email} readOnly={Boolean(email)} aria-invalid={Boolean(state.errors?.email)} aria-describedby={state.errors?.email ? `${id}-email-error` : undefined} />{state.errors?.email && <p id={`${id}-email-error`} className="field-error">{state.errors.email.join(" ")}</p>}</div>
    {addresses.length > 0 && <div><label htmlFor={`${id}-address`}>Adresse enregistrée</label><select id={`${id}-address`} name="addressId" value={addressId} onChange={event => setAddressId(event.target.value)}><option value="">Saisir une nouvelle adresse</option>{addresses.map(address => <option key={address.id} value={address.id}>{address.line1}, {address.city}{address.isDefault ? " (par défaut)" : ""}</option>)}</select><p className="form-help">Pour modifier les coordonnées, choisissez « Saisir une nouvelle adresse ».</p></div>}
    <fieldset key={addressId}><legend>Vos coordonnées · France</legend><div className="address-grid">{Object.entries(labels).map(([key, label]) => field(key, label, String(address?.[key as keyof Address] ?? (key === "firstName" ? firstName : key === "lastName" ? lastName : ""))))}</div></fieldset>
    <fieldset><legend>Mode de livraison</legend><label htmlFor={`${id}-shipping`}>Livraison</label><select id={`${id}-shipping`} name="shippingMethod" defaultValue={state.values?.shippingMethod ?? "STANDARD"}><option value="STANDARD">Standard · 3–5 jours · 5,90 €</option><option value="RELAY">Point relais fictif · 4,90 €</option><option value="EXPRESS">Express · 24 h · 9,90 €</option></select><p className="form-help">Livraison offerte dès 60 € après remise, pour les trois modes.</p><label htmlFor={`${id}-relay`}>Point relais (uniquement pour le mode relais)</label><select id={`${id}-relay`} name="relayPoint" defaultValue={state.values?.relayPoint ?? ""} aria-invalid={Boolean(state.errors?.relayPoint)} aria-describedby={`${id}-relay-help`}><option value="">Choisir un point fictif</option>{Object.entries(relayPoints).map(([key, point]) => <option key={key} value={key}>{point.city} · {point.zip} · Relais de démonstration</option>)}</select><p id={`${id}-relay-help`} className={state.errors?.relayPoint ? "field-error" : "form-help"}>{state.errors?.relayPoint?.join(" ") ?? "Ces points sont fictifs. Leurs coordonnées remplaceront l’adresse de livraison ; la facturation conservera vos coordonnées."}</p></fieldset>
    <details open={Boolean(Object.keys(state.errors ?? {}).some(key => key.startsWith("billing")))}><summary>Adresse de facturation différente (facultative)</summary><p>Laissez tous les champs vides pour utiliser vos coordonnées ci-dessus.</p><div className="address-grid">{Object.entries(labels).map(([key, label]) => field(key, label, "", true))}</div></details>
    <button className="cta" disabled={pending}>{pending ? "Préparation…" : "Continuer vers le paiement fictif"}</button></form>;
}
